import React from "react";
import Styled from "./Styled";

const Container = ({ children, ...component }) => {
  const data = component.block.data;
  const props = data.props;
  console.log("props", [data.props]);

  return (
    <Styled
      alignContent={props && props.alignItems && props.alignItems}
      alignItems={props && props.alignItems && props.alignItems}
      alignSelf={props && props.alignSelf && props.alignSelf}
      animation={props && props.animation && props.animation}
      animationDelay={props && props.animationDelay && props.animationDelay}
      animationDirection={props && props.animationDirection && props.animationDirection}
      animationDuration={props && props.animationDuration && props.animationDuration}
      animationFillMode={props && props.animationFillMode && props.animationFillMode}
      animationIterationCount={props && props.animationIterationCount && props.animationIterationCount}
      animationName={props &&props.animationName && props.animationName}
      animationPlayState={props &&props.animationPlayState && props.animationPlayState}
      animationTimingFunction={props &&props.animationTimingFunction && props.animationTimingFunction}
      backfaceVisibility={props &&props.backfaceVisibility && props.backfaceVisibility}
      background={props &&props.background && props.background}
      backgroundAttachment={props &&props.backgroundAttachment && props.backgroundAttachment}
      backgroundClip={props &&props.backgroundClip && props.backgroundClip}
      backgroundColor={props &&props.backgroundColor && props.backgroundColor}
      backgroundImage={props &&props.backgroundImage && props.backgroundImage}
      backgroundOrigin={props &&props.backgroundOrigin && props.backgroundOrigin}
      backgroundRepeat={props &&props.backgroundRepeat && props.backgroundRepeat}
      backgroundSize={props &&props.backgroundSize && props.backgroundSize}
      border={props &&props.border && props.border}
      bottom={props &&props.bottom && props.bottom}
      borderBottomColor={props && props.borderBottomColor && props.borderBottomColor}
      borderBottomLeftRadius={props &&props.borderBottomLeftRadius && props.borderBottomLeftRadius}
      borderBottomRightRadius={props &&props.borderBottomRightRadius && props.borderBottomRightRadius}
      borderBottomStyle={props &&props.borderBottomStyle && props.borderBottomStyle}
      borderBottomWidth={props &&props.borderBottomWidth && props.borderBottomWidth}
      borderCollapse={props &&props.borderCollapse && props.borderCollapse}
      borderColor={props &&props.borderColor && props.borderColor}
      borderImage={props &&props.borderImage && props.borderImage}
      borderImageOutset={props &&props.borderImageOutset && props.borderImageOutset}
      borderImageRepeat={props && props.borderImageRepeat && props.borderImageRepeat}
      borderImageSlice={props &&props.borderImageSlice && props.borderImageSlice}
      borderImageSource={props &&props.borderImageSource && props.borderImageSource}
      borderImageWidth={ props && props.borderImageWidth && props.borderImageWidth}
      borderLeftColor={ props && props.borderLeftColor && props.borderLeftColor}
      borderLeftStyle={ props && props.borderLeftStyle && props.borderLeftStyle}
      borderLeftWidth={ props && props.borderLeftWidth&& props.borderLeftWidth}
      borderRadius={ props && props.borderRadius && props.borderRadius}
      borderRight={ props && props.borderRight && props.borderRight}
      borderRightColor={ props && props.borderRightColor && props.borderRightColor}
      borderRightStyle={ props && props.borderRightStyle  && props.borderRightStyle}
      borderRightWidth={ props && props.borderRightWidth && props.borderRightWidth}
      borderSpacing={ props && props.borderSpacing  && props.borderSpacing}
      borderStyle={ props && props.borderStyle && props.borderStyle}
      borderTop={ props && props.borderTop && props.borderTop}
      borderTopColor={ props && props.borderTopColor && props.borderTopColor}
      borderTopLeftRadius={ props && props.borderTopLeftRadius && props.borderTopLeftRadius}
      borderTopRightRadius={ props && props.borderTopRightRadius && props.borderTopRightRadius}
      borderTopStyle={ props && props.borderTopStyle && props.borderTopStyle}
      borderTopWidth={ props &&props.borderTopWidth && props.borderTopWidth}
      borderWidth={ props && props.borderWidth&& props.borderWidth}
      bottom={ props && props.bottom&& props.bottom}
      boxShadow={ props && props.boxShadow&& props.boxShadow}
      boxSizing={ props && props.boxSizing&& props.boxSizing}
      captionSide={ props && props.captionSide&& props.captionSide}
      clear={ props && props.clear && props.clear}
      clip={ props && props.clip&& props.clip}
      color={ props && props.color&& props.color}
      columnCount={ props && props.columnCount&& props.columnCount}
      columnFill={ props && props.columnFill&& props.columnFill}
      columnGap={ props &&props.columnGap && props.columnGap}
      columnRule={ props && props.columnRule&& props.columnRule}
      columnRuleColor={ props && props.columnRuleColor&& props.columnRuleColor}
      columnRuleStyle={ props && props.columnRuleStyle&& props.columnRuleStyle}
      columnRuleWidth={ props && props.columnRuleWidth&& props.columnRuleWidth}
      columnSpan={ props && props.columnSpan&& props.columnSpan}
      columnWidth={ props && props.columnWidth&& props.columnWidth}
      columns={ props && props.columns&& props.columns}
      counterIncrement={ props && props.counterIncrement&& props.counterIncrement}
      counterReset={ props && props.counterReset && props.counterReset}
      cursor={ props && props.cursor && props.cursor}
      direction={ props && props.direction && props.direction}
      display={ props && props.display && props.display}
      emptyCells={ props && props.emptyCells && props.emptyCells}
      flex={ props && props.flex && props.flex}
      flexBasis={ props && props.flexBasis && props.flexBasis}
      flexDirection={ props && props.flexDirection && props.flexDirection}
      flexFlow={ props && props.flexFlow && props.flexFlow}
      flexGrow={ props && props.flexGrow && props.flexGrow}
      flexShrink={ props && props.flexShrink && props.flexShrink}
      flexWrap={ props && props.flexWrap && props.flexWrap}
      float={ props && props.float && props.float}
      font={ props && props.font && props.font}
      fontFamily={ props && props.fontFamily && props.fontFamily}
      fontSize={ props && props.fontSize && props.fontSize}
      fontSizeAdjust={ props && props.fontSizeAdjust && props.fontSizeAdjust}
      fontStretch={ props && props.fontStretch && props.fontStretch}
      fontStyle={ props && props.fontStyle && props.fontStyle}
      fontVariant={ props && props.fontVariant && props.fontVariant}
      fontWeight={ props && props.fontWeight && props.fontWeight}
      height={ props && props.height && props.height}
      justifyContent={ props && props.justifyContent && props.justifyContent}
      left={ props && props.left && props.left}
      letterSpacing={ props && props.letterSpacing && props.letterSpacing}
      lineHeight={ props && props.lineHeight && props.lineHeight}
      listStyle={ props && props.listStyle && props.listStyle}
      listStyleImage={ props && props.listStyleImage && props.listStyleImage}
      listStylePosition={ props && props.listStylePosition && props.listStylePosition}
      listStyleType={ props && props.listStyleType && props.listStyleType}
      margin={ props && props.margin && props.margin}
      marginBottom={ props && props.marginBottom && props.marginBottom}
      marginLeft={ props && props.marginLeft && props.marginLeft}
      marginRight={ props && props.marginRight && props.marginRight}
      marginTop={ props && props.marginTop && props.marginTop}
      maxHeight={ props && props.maxHeight && props.maxHeight}
      maxWidth={ props && props.maxWidth && props.maxWidth}
      minHeight={ props && props.minHeight && props.minHeight}
      minWidth={ props && props.minWidth && props.minWidth}
      opacity={ props && props.opacity && props.opacity}
      order={ props && props.order && props.order}
      outline={ props && props.outline && props.outline}
      outlineColor={ props && props.outlineColor && props.outlineColor}
      outlineOffset={ props && props.outlineOffset&& props.outlineOffset}
      outlineOutlineStyle={ props && props.outlineOutlineStyle && props.outlineOutlineStyle}
      outlineWidth={ props && props.outlineWidth && props.outlineWidth}
      overflow={ props && props.overflow && props.overflow}
      overflowX={ props && props.overflowX && props.overflowX}
      overflowY={ props && props.overflowY && props.overflowY}
      padding={ props && props.padding && props.padding}
      paddingBottom={ props && props.paddingBottom && props.paddingBottom}
      paddingLeft={ props && props.paddingBottom && props.paddingLeft}
      paddingRight={ props && props.paddingRight && props.paddingRight}
      paddingTop={ props && props.paddingTop && props.paddingTop}
      pageBreakAfter={ props && props.pageBreakAfter && props.pageBreakAfter}
      pageBreakBefore={ props && props.pageBreakBefore && props.pageBreakBefore}
      pageBreakInside={ props && props.pageBreakInside && props.pageBreakInside}
      perspective={ props && props.perspective && props.perspective}
      perspectiveOrigin={ props && props.perspectiveOrigin && props.perspectiveOrigin}
      position={ props && props.position && props.position}
      quotes={ props && props.quotes && props.quotes}
      resize={ props && props.resize && props.resize}
      right={ props && props.right && props.right}
      tabSize={ props && props.tabSize && props.tabSize}
      tableLayout={ props && props.tableLayout && props.tableLayout}
      textAlign={ props && props.textAlign && props.textAlign}
      textAlignLast={ props && props.textAlignLast && props.textAlignLast}
      textDecoration={ props && props.textDecoration && props.textDecoration}
      textDecorationColor={ props && props.textDecorationColor && props.textDecorationColor}
      textDecorationLine={ props && props.textDecorationLine && props.textDecorationLine}
      textDecorationStyle={ props && props.textDecorationStyle && props.textDecorationStyle}
      textIndent={ props && props.textIndent && props.textIndent}
      textJustify={ props && props.textJustify && props.textJustify}
      textOverflow={ props && props.textOverflow && props.textOverflow}
      textShadow={ props && props.textShadow && props.textShadow}
      textTransform={ props && props.textTransform && props.textTransform}
      top={ props && props.top && props.top}
      transform={ props && props.transform && props.transform}
      transformOrigin={ props && props.transformOrigin && props.transformOrigin}
      transformStyle={ props && props.transformStyle && props.transformStyle}
      transition={ props && props.transition && props.transition}
      transitionDelay={ props && props.transitionDelay && props.transitionDelay}
      transitionDuration={ props && props.transitionDelay && props.transitionDuration}
      transitionProperty={ props && props.transitionDelay && props.transitionProperty}
      transitionTimingFunction={ props && props.transitionDelay && props.transitionTimingFunction}
      verticalAlign={ props && props.transitionDelay && props.verticalAlign}
      visibility={ props && props.transitionDelay && props.visibility}
      whiteSpace={ props && props.transitionDelay && props.whiteSpace}
      width={ props && props.transitionDelay && props.width}
      wordBreak={ props && props.transitionDelay && props.wordBreak}
      wordSpacing={ props && props.transitionDelay && props.wordSpacing}
      wordWrap={ props && props.transitionDelay && props.wordWrap}
      borderBottomRightRadius={ props && props.transitionDelay && props.zIndex}
      as={"div"}
    >
      Container
      <div>{children}</div>
    </Styled>
  );
};

export default Container;
